"""
fusion360_bridge.py — Autodesk Platform Services (APS) bridge for cad-mcp.

Connects to Autodesk Platform Services (formerly Autodesk Forge) to:
  1. Upload STEP/STL models generated by CadQuery
  2. Translate them to viewable formats (SVF2, OBJ, thumbnail PNG)
  3. Retrieve rendered thumbnails
  4. Query model properties (mass, materials, bounding box)
  5. Trigger Fusion 360 Design Automation scripts in the cloud

Authentication: 2-legged OAuth (client_credentials)
Required env vars:
    APS_CLIENT_ID      — from Autodesk Platform Services app
    APS_CLIENT_SECRET  — from Autodesk Platform Services app
    APS_BUCKET_KEY     — OSS bucket to use (created automatically)

Setup:
    1. Go to https://aps.autodesk.com/
    2. Create an App → get Client ID + Client Secret
    3. Set env vars:
         $env:APS_CLIENT_ID     = "your_client_id"
         $env:APS_CLIENT_SECRET = "your_client_secret"
         $env:APS_BUCKET_KEY    = "cad-mcp-models"   # any unique bucket name
"""

from __future__ import annotations

import base64
import json
import logging
import os
import time
from pathlib import Path
from typing import Any

log = logging.getLogger("cadquery_server.fusion360_bridge")

# ── APS / Forge API base URLs ─────────────────────────────────────────────
APS_BASE        = "https://developer.api.autodesk.com"
AUTH_URL        = f"{APS_BASE}/authentication/v2/token"
BUCKETS_URL     = f"{APS_BASE}/oss/v2/buckets"
DERIVATIVES_URL = f"{APS_BASE}/modelderivative/v2/designdata"

# ── Config from environment ────────────────────────────────────────────────
CLIENT_ID     = os.environ.get("APS_CLIENT_ID", "")
CLIENT_SECRET = os.environ.get("APS_CLIENT_SECRET", "")
BUCKET_KEY    = os.environ.get("APS_BUCKET_KEY", "cad-mcp-models")

# ── Translation poll settings ──────────────────────────────────────────────
TRANSLATION_POLL_INTERVAL_S = 5
TRANSLATION_MAX_WAIT_S      = 300  # 5 minutes


# ---------------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------------

_token_cache: dict[str, Any] = {}


def _get_access_token() -> str:
    """
    Obtain a 2-legged OAuth token using client_credentials.
    Caches the token until 60s before expiry.
    """
    try:
        import requests  # type: ignore[import-untyped]
    except ImportError:
        raise ImportError("requests is required: pip install requests")

    now = time.time()
    cached = _token_cache
    if cached.get("token") and cached.get("expires_at", 0) > now + 60:
        return str(cached["token"])

    if not CLIENT_ID or not CLIENT_SECRET:
        raise EnvironmentError(
            "APS_CLIENT_ID and APS_CLIENT_SECRET must be set.\n"
            "Get them at https://aps.autodesk.com/ → Create App."
        )

    resp = requests.post(
        AUTH_URL,
        data={
            "grant_type":    "client_credentials",
            "scope":         "data:read data:write data:create bucket:create bucket:read",
            "client_id":     CLIENT_ID,
            "client_secret": CLIENT_SECRET,
        },
        timeout=15,
    )
    resp.raise_for_status()
    data = resp.json()
    _token_cache["token"]      = data["access_token"]
    _token_cache["expires_at"] = now + int(data.get("expires_in", 3600))
    log.info("APS: obtained access token (expires in %ds)", data.get("expires_in", 3600))
    return str(_token_cache["token"])


def _headers(token: str, extra: dict[str, str] | None = None) -> dict[str, str]:
    h = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    if extra:
        h.update(extra)
    return h


# ---------------------------------------------------------------------------
# Bucket management
# ---------------------------------------------------------------------------

def _ensure_bucket(token: str) -> None:
    """Create the OSS bucket if it doesn't already exist."""
    import requests  # type: ignore[import-untyped]

    resp = requests.get(
        f"{BUCKETS_URL}/{BUCKET_KEY}/details",
        headers=_headers(token),
        timeout=15,
    )
    if resp.status_code == 200:
        return  # exists
    if resp.status_code != 404:
        resp.raise_for_status()

    # Create
    resp = requests.post(
        BUCKETS_URL,
        headers=_headers(token),
        json={
            "bucketKey": BUCKET_KEY,
            "policyKey": "transient",  # files auto-deleted after 24h
        },
        timeout=15,
    )
    if resp.status_code not in (200, 409):  # 409 = already exists
        resp.raise_for_status()
    log.info("APS: bucket '%s' ready.", BUCKET_KEY)


# ---------------------------------------------------------------------------
# Upload model
# ---------------------------------------------------------------------------

def upload_model(file_path: str, object_name: str) -> str:
    """
    Upload a file to APS Object Storage (OSS).

    Returns the base64-encoded URN for use with Model Derivative API.
    """
    import requests  # type: ignore[import-untyped]

    token = _get_access_token()
    _ensure_bucket(token)

    path = Path(file_path)
    file_size = path.stat().st_size

    log.info("APS upload: %s (%d bytes) → bucket '%s'", path.name, file_size, BUCKET_KEY)

    with open(path, "rb") as fh:
        resp = requests.put(
            f"{BUCKETS_URL}/{BUCKET_KEY}/objects/{object_name}",
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/octet-stream",
                "Content-Length": str(file_size),
            },
            data=fh,
            timeout=120,
        )
    resp.raise_for_status()
    data = resp.json()
    object_id = data.get("objectId", "")
    urn = base64.urlsafe_b64encode(object_id.encode()).decode().rstrip("=")
    log.info("APS upload complete. URN: %s…", urn[:20])
    return urn


# ---------------------------------------------------------------------------
# Model Derivative — translate
# ---------------------------------------------------------------------------

def translate_model(urn: str, output_format: str = "svf2") -> dict[str, Any]:
    """
    Submit a translation job via APS Model Derivative API.
    Supported outputs: svf2 (Forge Viewer), obj, stl, thumbnail.
    Returns the manifest after translation completes.
    """
    import requests  # type: ignore[import-untyped]

    token = _get_access_token()

    # Submit job
    payload: dict[str, Any] = {
        "input":  {"urn": urn},
        "output": {
            "formats": [
                {"type": output_format, "views": ["2d", "3d"]}
                if output_format == "svf2"
                else {"type": output_format}
            ]
        },
    }
    resp = requests.post(
        f"{DERIVATIVES_URL}/job",
        headers=_headers(token),
        json=payload,
        timeout=30,
    )
    resp.raise_for_status()
    log.info("APS: translation job submitted for URN %s…", urn[:20])

    # Poll for completion
    started = time.time()
    while time.time() - started < TRANSLATION_MAX_WAIT_S:
        time.sleep(TRANSLATION_POLL_INTERVAL_S)
        manifest_resp = requests.get(
            f"{DERIVATIVES_URL}/{urn}/manifest",
            headers=_headers(token),
            timeout=15,
        )
        if manifest_resp.status_code == 404:
            time.sleep(TRANSLATION_POLL_INTERVAL_S)
            continue
        manifest_resp.raise_for_status()
        manifest = manifest_resp.json()
        status = manifest.get("status", "pending")
        progress = manifest.get("progress", "0%")
        log.info("APS translation: status=%s progress=%s", status, progress)
        if status == "success":
            return manifest
        if status == "failed":
            raise RuntimeError(f"APS translation failed: {manifest.get('derivatives', [])}")

    raise TimeoutError(f"APS translation timed out after {TRANSLATION_MAX_WAIT_S}s")


# ---------------------------------------------------------------------------
# Thumbnail retrieval
# ---------------------------------------------------------------------------

def get_thumbnail(urn: str, output_path: str, width: int = 400, height: int = 400) -> str:
    """
    Download a rendered thumbnail PNG for the model.
    Returns the path to the saved PNG file.
    """
    import requests  # type: ignore[import-untyped]

    token = _get_access_token()
    resp = requests.get(
        f"{DERIVATIVES_URL}/{urn}/thumbnail",
        headers={
            "Authorization": f"Bearer {token}",
        },
        params={"width": width, "height": height},
        timeout=30,
    )
    resp.raise_for_status()

    Path(output_path).write_bytes(resp.content)
    log.info("APS thumbnail saved to %s (%d bytes)", output_path, len(resp.content))
    return output_path


# ---------------------------------------------------------------------------
# Model properties (mass, material, bounding box via Model Derivative)
# ---------------------------------------------------------------------------

def get_model_properties(urn: str) -> dict[str, Any]:
    """
    Retrieve model properties (mass, volume, bounding box, materials)
    from the Model Derivative API after translation.
    """
    import requests  # type: ignore[import-untyped]

    token = _get_access_token()

    # Get object tree first
    resp = requests.get(
        f"{DERIVATIVES_URL}/{urn}/metadata",
        headers=_headers(token),
        timeout=15,
    )
    resp.raise_for_status()
    meta = resp.json()
    guids = [v["guid"] for v in meta.get("data", {}).get("metadata", [])]

    if not guids:
        return {"properties": [], "note": "No 3D viewables found in this model."}

    # Grab properties from the first 3D view
    guid = guids[0]
    resp = requests.get(
        f"{DERIVATIVES_URL}/{urn}/metadata/{guid}/properties",
        headers=_headers(token),
        timeout=30,
    )
    resp.raise_for_status()
    props_data = resp.json()
    return {
        "urn": urn,
        "properties": props_data.get("data", {}).get("collection", []),
        "source": "Autodesk Platform Services Model Derivative",
    }


# ---------------------------------------------------------------------------
# Design Automation — run Fusion 360 cloud script
# ---------------------------------------------------------------------------

def run_fusion360_script(
    urn: str,
    script: str,
    activity_id: str = "Autodesk.Fusion360DA+latest$",
) -> dict[str, Any]:
    """
    Run a Fusion 360 Design Automation script on a model.

    Parameters
    ----------
    urn         Base64 URN of the uploaded model.
    script      Python script content to execute in Fusion 360.
    activity_id APS Design Automation activity (default: Fusion 360).

    Returns the work item result.
    """
    import requests  # type: ignore[import-untyped]

    token = _get_access_token()
    da_url = f"{APS_BASE}/da/us-east/v3"

    payload = {
        "activityId":  activity_id,
        "arguments": {
            "HostDwg": {
                "url":  f"urn:adsk.objects:os.object:{BUCKET_KEY}/input.f3d",
                "verb": "get",
            },
            "Result": {
                "url":  f"urn:adsk.objects:os.object:{BUCKET_KEY}/result.f3d",
                "verb": "put",
            },
            "Script": {"url": f"data:text/plain,{script}"},
        },
    }

    resp = requests.post(
        f"{da_url}/workitems",
        headers=_headers(token),
        json=payload,
        timeout=30,
    )
    resp.raise_for_status()
    work_item = resp.json()
    wi_id = work_item.get("id", "")
    log.info("Design Automation work item submitted: %s", wi_id)

    # Poll
    started = time.time()
    while time.time() - started < 600:
        time.sleep(10)
        status_resp = requests.get(
            f"{da_url}/workitems/{wi_id}",
            headers=_headers(token),
            timeout=15,
        )
        status_resp.raise_for_status()
        wi_status = status_resp.json()
        state = wi_status.get("status", "pending")
        log.info("Design Automation: %s", state)
        if state == "success":
            return wi_status
        if state in ("failed", "cancelled", "timedout"):
            raise RuntimeError(f"Design Automation failed: {wi_status.get('reportUrl', '')}")

    raise TimeoutError("Design Automation work item timed out after 10 minutes.")


# ---------------------------------------------------------------------------
# APS credentials check
# ---------------------------------------------------------------------------

def check_credentials() -> dict[str, Any]:
    """Check if APS credentials are configured and valid."""
    if not CLIENT_ID or not CLIENT_SECRET:
        return {
            "configured": False,
            "error": "APS_CLIENT_ID and APS_CLIENT_SECRET environment variables are not set.",
            "instructions": (
                "1. Go to https://aps.autodesk.com/ → Sign in\n"
                "2. Click 'My Apps' → 'Create App'\n"
                "3. Give your app a name, select APIs (Data Management + Model Derivative)\n"
                "4. Copy Client ID and Client Secret\n"
                "5. Set env vars: APS_CLIENT_ID, APS_CLIENT_SECRET, APS_BUCKET_KEY"
            ),
        }
    try:
        token = _get_access_token()
        return {
            "configured": True,
            "client_id": CLIENT_ID[:8] + "...",
            "bucket_key": BUCKET_KEY,
            "token_preview": token[:12] + "...",
        }
    except Exception as exc:
        return {"configured": False, "error": str(exc)}
